config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
  resources :homes


  get '/buys/apartments', to: 'buys#all_apartments'
  get '/buys/independents', to: 'buys#all_independents'
  resources :buys

  get '/rents/apartments', to: 'rents#all_apartments'
  get '/rents/independents', to: 'rents#all_independents'
  resources :rents

   resources :comments
end

app/models/rent.rb
class Rent < ApplicationRecord
    has_many :comments, as: :commentable
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
    before_action :set_rent, only: [:edit,:update,:show,:destroy]

    def index
        @rents = Rent.all
    end

    def create
        @rent = Rent.new(rent_params)

        if @rent.save
            redirect_to rents_path, notice: "Property has been created succesfully"
        else
            render :new
        end
    end

    def new
        @rent = Rent.new
    end

    def edit
    end

    def update
        if @rent.update(rent_params) 
            redirect_to rents_path, notice: "Property has been updated succesfully"
        else
            render :edit #we can also use in string format like (render 'edit')
        end 
    end

    def show
    end

    def destroy
        if @rent.destroy
			redirect_to rents_path, notice: "Property has been Deleted succesfully"
		end
    end 

    def all_apartments
        @rents = Rent.where(property_type: "Apartment")
    end

    def all_independents
        @rents = Rent.where(property_type: "Independent")
    end


    private

    #callbacks
    def set_rent   
        @rent = Rent.find(params[:id])
    end

    #params
    def rent_params
        params.require(:rent).permit(:about,:add,:price,:phone_no,:property_type,:landmark)
    end
end
 

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_with(model: @rent, data: {turbo: false}) do |form|%>
    <div class="row">

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :about, class: 'mb-2'%>
                <%= form.text_field :about, class: 'form-control form-control-lg rounded-0'%>
                <% @rent.errors.full_messages_for(:about).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %> 
            </div>
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :price, class: 'mb-2'%>
                <%= form.number_field  :price, class: 'form-control form-control-lg rounded-0'%>

                <% @rent.errors.full_messages_for(:price).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <%= form.label :add, class: 'mb-2 mt-4'%>
                <%= form.text_field  :add, class: 'form-control form-control-lg rounded-0'%>

                <% @rent.errors.full_messages_for(:add).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :phone_no, class: 'mb-2 mt-4'%>
                <%= form.telephone_field :phone_no, class: 'form-control form-control-lg rounded-0'%>

                <% @rent.errors.full_messages_for(:phone_no).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :landmark, class: 'mb-2 mt-4'%>
                <%= form.text_field :landmark, class: 'form-control form-control-lg rounded-0'%>

                <% @rent.errors.full_messages_for(:landmark).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :property_type, class: 'mb-2 mt-4'%><br>
                <%= form.select :property_type, [["Apartment", "Apartment"], ["Independent", "Independent"]],class: 'form-select form-select-lg mb-3' %>

               <% @rent.errors.full_messages_for(:property_type).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12 mt-4">
            <%= form.submit class: 'btn btn-primary btn-lg rounded-0'%>
            <%= link_to "Back to rent", rents_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
            </div>
    </div>

<% end %>

app/views/rents/_rentListTable.html.erb
<table class="table table-bordered table-striped border-info">
        <thead>
            <tr>
                <th>ID</th>
                <th>About</th>
                <th>Price</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Property Type</th>
                <th>Landmark</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            <% @rents.each do |r| %>
                <tr>
                    <td> <%= r.id%> </td>
                    <td> <%= r.about %> </td>
                    <td> <%= r.price%> </td>
                    <td> <%= r.add%> </td>
                    <td> <%= r.phone_no%> </td>
                    <td> <%= r.property_type%> </td>
                    <td> <%= r.landmark%> </td>
                    <td> 


                    <a href="/rents/<%= r.id %>" class="btn btn-primary btn-lg ">Show</a>
                    
                    </td>
                </tr>   
            <% end %>
        </tbody>
    </table>

app/views/rents/all_apartments.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-dark bg-gradient text-white">
        <div class="card-body ">
        <h1 class="text-center">Listing All The Rent Apartments Property</h1>
        </div>
    </div>

    <%= render 'rentListTable' %>
</div>

app/views/rents/all_independents.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-dark bg-gradient text-white">
        <div class="card-body ">
        <h1 class="text-center">Listing All The Rent Independent Property</h1>
        </div>
    </div>

    <%= render 'rentListTable' %>
</div>

app/views/rents/edit.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-4 bg-info">
        <div class="card-body ">
        <h1 class="text-center ">Edit Rent Information </h1>
        </div>
    </div>


    <%= render 'form', rent: @rent%>

</div>

app/views/rents/index.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-info text-white">
        <div class="card-body bg-dark bg-gradient ">
        <h1 class="text-center ">Listing All The Rent Property</h1>
        </div>
    </div>

    <%= link_to "Create New Property", new_rent_path,class: "btn btn-primary btn-lg mb-4"%>

    <table class="table table-bordered table-striped border-info">
        <thead>
            <tr>
                <th>ID</th>
                <th>About</th>
                <th>Price</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Property Type</th>
                <th>Landmark</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @rents.each do |r| %>
                <tr>
                    <td> <%= r.id%> </td>
                    <td> <%= r.about %> </td>
                    <td> <%= r.price%> </td>
                    <td> <%= r.add%> </td>
                    <td> <%= r.phone_no%> </td>
                    <td> <%= r.property_type%> </td>
                    <td> <%= r.landmark%> </td>
                    <td> 


                        <!-- Example single danger button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-outline-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Action
                            </button>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Edit", edit_rent_path(r), class: 'dropdown-item bg-outline-primary border' %></li>
                                <li><a href="/rents/<%= r.id %>" class="dropdown-item bg-outline-info border">Show</a></li>
                                <li><%= link_to "Delete", rent_path(r), class: "dropdown-item bg-outline-danger ",method: :delete, data: { confirm: 'Are you sure to delete this content ? '}%></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><%= link_to "Something else", nil,class: " dropdown-item bg-outline-danger"%></li>
                            </ul>
                        </div>
                    
                    </td>
                </tr>   
            <% end %>
        </tbody>
    </table>
</div>

app/views/rents/new.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-4">
        <div class="card-body bg-dark bg-gradient text-light">
        <h1 class="text-center ">Create Rent Property </h1>
        </div>
    </div>

<%= render 'form', rent: @rent%>
</div>

app/views/rents/show.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body ">
            <h1 class="text-center mb-5 me-5 bg-dark bg-gradient text-white"> Rent Property Details </h1>
            <div class="row">
                <div class="col-lg-6">
                    <h3 class="ms-5 bg-info">Rent Property Information</h3>
                    <p class="lead ms-5"><strong>ID: </strong><%= @rent.id %></p>
                    <p class="lead ms-5"><strong>About: </strong><%= @rent.about %></p>
                    <p class="lead ms-5"><strong>Price: </strong><%= @rent.price.present? ? @rent.price : '--NA--' %></p>
                    <p class="lead ms-5"><strong>Address: </strong><%= @rent.add %></p>                    
                    <p class="lead ms-5"><strong>Phone Number: </strong><%= @rent.phone_no %></p>
                    <p class="lead ms-5"><strong>Property Type: </strong><%= @rent.property_type %></p>
                    <p class="lead ms-5"><strong>Landmark: </strong><%= @rent.landmark %></p>
                </div>
                <div class="col-lg-6">
                    <h3 class="ms-5 bg-info">Address Information</h3>    
                    <p class="lead ms-5"><strong>Address: </strong><%= @rent.add %></p>                    
                    <p class="lead ms-5"><strong>Landmark: </strong><%= @rent.landmark %></p>               
                </div>
            </div>
        </div>
    </div> 


    <%= link_to 'Edit Rent',edit_rent_path, class: 'btn btn-primary btn-lg' %>

    <%= link_to 'Back to rent',rents_path, class: 'btn btn-outline-primary btn-lg ' %>

</div>


<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body ">
            <% if @rent.comments.present?%>
                <div class="row">
                    <h1 class="text-center mt-4 me-5 bg-dark bg-gradient text-white"> Rent Property Comments </h1> 

                        <div class='col-lg-4'>
                            <p class='lead ms-3'><h4>Content</h4></p>
                        </div>
                            
                </div>
                <% @rent.comments.each do |comment|%>
                        
                    <div class="card mb-4">
                        <div class="card-body ">
                            <div class="row">

                                <div class='col-lg-4'>
                                    <p class='lead'> <%= comment.content %> </p>
                                </div>
                                        
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>