config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
  resources :homes


  get '/buys/apartments', to: 'buys#all_apartments'
  get '/buys/independents', to: 'buys#all_independents'
  resources :buys

  get '/rents/apartments', to: 'rents#all_apartments'
  get '/rents/independents', to: 'rents#all_independents'
  resources :rents

   resources :comments
end

app/models/buy.rb
class Buy < ApplicationRecord
    has_many :comments, as: :commentable
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
    before_action :set_buy, only: [:edit,:update,:show,:destroy]

    def index
        @buys = Buy.all
    end

    def create
        @buy = Buy.new(buy_params)
        
        if @buy.save
            redirect_to buys_path, notice: "Property has been created succesfully"
        else
            render :new 
        end
    end

    def new
        @buy = Buy.new
    end

    def edit
    end

    def update
        if @buy.update(buy_params) 
            redirect_to buys_path, notice: "Property has been updated succesfully"
        else
            render :edit #we can also use in string format like (render 'edit')
        end 
    end

    def show
       
    end

    def destroy
        if @buy.destroy
			redirect_to buys_path, notice: "Property has been Deleted succesfully"
		end
    end 

    def all_apartments
        @buys = Buy.where(property_type: "Apartment")
    end

    def all_independents
        @buys = Buy.where(property_type: "Independent")
    end


    private

    #callbacks
    def set_buy   
        @buy = Buy.find(params[:id])
    end

    #params
    def buy_params
        params.require(:buy).permit(:about,:add,:price,:phone_no,:property_type,:landmark)
    end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_buyListTable.html.erb
<table class="table table-bordered table-striped border-info">
        <thead>
            <tr>
                <th>ID</th>
                <th>About</th>
                <th>Price</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Property Type</th>
                <th>Landmark</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @buys.each do |b| %>
                <tr>
                    <td> <%= b.id%> </td>
                    <td> <%= b.about %> </td>
                    <td> <%= b.price%> </td>
                    <td> <%= b.add%> </td>
                    <td> <%= b.phone_no%> </td>
                    <td> <%= b.property_type%> </td>
                    <td> <%= b.landmark%> </td>
                    <td> 


                    <a href="/buys/<%= b.id %>" class="btn btn-primary btn-lg ">Show</a>
                    
                    </td>
                </tr>   
            <% end %>
        </tbody>
    </table>

app/views/buys/_form.html.erb
<%= form_with(model: @buy, data: {turbo: false}) do |form|%>
    <div class="row">

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :about, class: 'mb-2'%>
                <%= form.text_field :about, class: 'form-control form-control-lg rounded-0'%>
                <% @buy.errors.full_messages_for(:about).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %> 
            </div>
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :price, class: 'mb-2'%>
                <%= form.number_field  :price, class: 'form-control form-control-lg rounded-0'%>

                <% @buy.errors.full_messages_for(:price).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <%= form.label :add, class: 'mb-2 mt-4'%>
                <%= form.text_field  :add, class: 'form-control form-control-lg rounded-0'%>

                <% @buy.errors.full_messages_for(:add).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :phone_no, class: 'mb-2 mt-4'%>
                <%= form.telephone_field :phone_no, class: 'form-control form-control-lg rounded-0'%>

                <% @buy.errors.full_messages_for(:phone_no).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>
        
        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :landmark, class: 'mb-2 mt-4'%>
                <%= form.text_field :landmark, class: 'form-control form-control-lg rounded-0'%>

                <% @buy.errors.full_messages_for(:landmark).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>

        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :property_type, class: 'mb-2 mt-4'%><br>
                <%= form.select :property_type, [["Apartment", "Apartment"], ["Independent", "Independent"]],class: 'form-select form-select-lg mb-3' %>

               <% @buy.errors.full_messages_for(:property_type).each do |message| %>
                    <p class="text-danger"><%= message %></p>  
                <% end %>

            </div>
        </div>


    </div>

    <div class="row">
        <div class="col-lg-12 mt-4">
            <%= form.submit 'Update Property', class: 'btn btn-primary btn-lg rounded-0'%>
            <%= link_to "Back to Property", buys_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
            </div>
    </div>

<% end %>

app/views/buys/all_apartments.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-dark bg-gradient text-white">
        <div class="card-body ">
        <h1 class="text-center">Listing All The Selling Apartments</h1>
        </div>
    </div>

    <%= render 'buyListTable'%>

</div>

app/views/buys/all_independents.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-dark bg-gradient text-white">
        <div class="card-body ">
        <h1 class="text-center">Listing All The Selling Independent Property</h1>
        </div>
    </div>

    <%= render 'buyListTable'%>
</div>

app/views/buys/edit.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-4 bg-info">
        <div class="card-body ">
        <h1 class="text-center ">Edit Property Information </h1>
        </div>
    </div>


    <%= render 'form', buy: @buy%>

</div>

app/views/buys/index.html.erb
<div class="col-lg-12">

    <div class="card rounded-0 mt-3 mb-4 bg-info text-white">
        <div class="card-body bg-dark bg-gradient ">
        <h1 class="text-center ">Listing All The Selling Property</h1>
        </div>
    </div>

    <%= link_to "Create New Property", new_buy_path,class: "btn btn-primary btn-lg mb-4"%>

    <table class="table table-bordered table-striped border-info">
        <thead>
            <tr>
                <th>ID</th> 
                <th>About</th>
                <th>Price</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Property Type</th>
                <th>Landmark</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @buys.each do |b| %>
                <tr>
                    <td> <%= b.id%> </td>
                    <td> <%= b.about %> </td>
                    <td> <%= b.price%> </td>
                    <td> <%= b.add%> </td>
                    <td> <%= b.phone_no%> </td>
                    <td> <%= b.property_type%> </td>
                    <td> <%= b.landmark%> </td>
                    <td> 


                        <!-- Example single danger button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-outline-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Action
                            </button>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Edit", edit_buy_path(b), class: 'dropdown-item bg-outline-primary border' %></li>
                                <li><a href="/buys/<%= b.id %>" class="dropdown-item bg-outline-info border">Show</a></li>
                                <li><%= link_to "Delete", buy_path(b), class: "dropdown-item bg-outline-danger ",method: :delete, data: { confirm: 'Are you sure to delete this content ? '}%></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><%= link_to "Something else", nil,class: " dropdown-item bg-outline-danger"%></li>
                            </ul>
                        </div>
                    
                    </td>
                </tr>   
            <% end %>
        </tbody>
    </table>    
</div>

app/views/buys/new.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-4">
        <div class="card-body bg-dark bg-gradient text-light">
        <h1 class="text-center ">Create Property </h1>
        </div>
    </div>

<%= render 'form', buy: @buy%>
</div>

app/views/buys/show.html.erb
<div class="col-lg-12">
    
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body ">
            <h1 class="text-center mb-5 me-5 bg-dark bg-gradient text-white"> Property Details </h1>
            <div class="row">
                <div class="col-lg-6">
                    <h3 class="ms-5 bg-info">Property Information</h3>
                    <p class="lead ms-5"><strong>ID: </strong><%= @buy.id %></p>
                    <p class="lead ms-5"><strong>About: </strong><%= @buy.about %></p>
                    <p class="lead ms-5"><strong>Price: </strong><%= @buy.price.present? ? @buy.price : '--NA--' %></p>
                    <p class="lead ms-5"><strong>Address: </strong><%= @buy.add %></p>                    
                    <p class="lead ms-5"><strong>Phone Number: </strong><%= @buy.phone_no %></p>
                    <p class="lead ms-5"><strong>Property Type: </strong><%= @buy.property_type %></p>
                    <p class="lead ms-5"><strong>Landmark: </strong><%= @buy.landmark %></p>
                </div>
                <div class="col-lg-6">
                    <h3 class="ms-5 bg-info">Address Information</h3>    
                    <p class="lead ms-5"><strong>Address: </strong><%= @buy.add %></p>                    
                    <p class="lead ms-5"><strong>Landmark: </strong><%= @buy.landmark %></p>               
                </div>
            </div>
        </div>
    </div> 


    <%= link_to 'Edit Property',edit_buy_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Back to Property',buys_path, class: 'btn btn-outline-primary btn-lg ' %>
    <%= link_to 'Create Comment', new_comment_path(buy_id: @buy.id), class: 'btn btn-outline-primary btn-lg' %>

</div>



<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body ">
            <% if @buy.comments.present?%>
                <div class="row">
                    <h1 class="text-center mt-4 me-5 bg-dark bg-gradient text-white">Property Comments </h1> 

                        <div class='col-lg-6'>
                            <p class='lead ms-3'><h4>Content</h4></p>
                        </div>

                        <div class='col-lg-4'>
                            <p class='lead ms-3'><h4>ID</h4></p>
                        </div>
                            
                </div>
                <% @buy.comments.each do |comment|%>
                        
                    <div class="card mb-4">
                        <div class="card-body ">
                            <div class="row">

                                <div class='col-lg-6'>
                                    <p class='lead'> <%= comment.content %> </p>
                                </div>

                                <div class='col-lg-4'>
                                    <p class='lead'> <%= comment.id %> </p>
                                </div>
                                
                                <div class='col-lg-2'>
                                <%= link_to 'Delete',comment_path(comment.id), method: :delete, class: 'btn btn-outline-primary btn-lg' %>
                                <%= link_to 'edit',edit_comment_path(comment.id), class: 'btn btn-outline-primary btn-lg' %>

                                </div>

                            </div>
                        </div>
                    </div>
                <% end %>
                    
            <% end %>
    </div>
</div>
</div>